from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import pandas as pd
from typing import Optional

app = FastAPI(title="PA Best Restaurants API")

#Allowing the  frontend to call from any origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

#Load data with predictions generated by the best model
df = pd.read_csv("restaurants_with_predictions.csv")

#Root endpoint – gives an overview of the API
@app.get("/")
def root():
    return JSONResponse(content={
        "message": "Welcome to the PA Best Restaurants API",
        "endpoints": {
            "/restaurants": "Get ranked restaurants with optional filters (city, cuisine, price_min, price_max, top_n)",
            "/docs": "Interactive API documentation (Swagger UI)",
            "/redoc": "Alternative API documentation (ReDoc)"
        },
        "example": "/restaurants?city=Pittsburgh&cuisine=mexican&top_n=5"
    })

@app.get("/restaurants")
def get_restaurants(
    city: Optional[str] = None,
    cuisine: Optional[str] = None,
    price_min: Optional[int] = None,
    price_max: Optional[int] = None,
    top_n: int = 10
):
    data = df.copy()

    if city:
        data = data[data['city'].str.contains(city, case=False, na=False)]

    if cuisine:
        col_name = f"cat_{cuisine}_restaurant"
        if col_name not in data.columns:
            col_name = f"cat_{cuisine}"
        if col_name in data.columns:
            data = data[data[col_name] == 1]

    if price_min is not None:
        data = data[data['price_level'] >= price_min]
    if price_max is not None:
        data = data[data['price_level'] <= price_max]

    data = data.sort_values('predicted_rating', ascending=False).head(top_n)

    return data[['title', 'city', 'address', 'price_level', 'rating', 'predicted_rating',
                 'category', 'reviews_total_count']].to_dict(orient='records')

if __name__ == "__main__":
    import uvicorn
    print("Starting server...")
    print("API documentation available at http://localhost:8000/docs")
    print("Root endpoint: http://localhost:8000/")
    uvicorn.run(app, host="0.0.0.0", port=8000)