from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, HTMLResponse
import pandas as pd
import numpy as np
from typing import Optional

app = FastAPI(title="PA Best Restaurants API")

#Allowing the  frontend to call from any origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

#Load data with predictions generated by the best model
df = pd.read_csv("restaurants_with_predictions.csv")

#Remove any infinite values at the source
df = df.replace([np.inf, -np.inf], np.nan)

#Helper function to convert a row to JSON-serializable dict
def make_serializable(row):
    record = {}
    for col in row.index:
        val = row[col]
        if pd.isna(val) or (isinstance(val, float) and (np.isinf(val) or np.isnan(val))):
            record[col] = None
        elif isinstance(val, (np.integer, np.int64)):
            record[col] = int(val)
        elif isinstance(val, (np.floating, np.float64)):
            fval = float(val)
            if np.isinf(fval) or np.isnan(fval):
                record[col] = None
            else:
                record[col] = fval
        else:
            record[col] = val
    return record

#Root endpoint – serves the HTML frontend for easy access
@app.get("/")
def root():
    try:
        with open("restaurant_finder.html", "r", encoding="utf-8") as f:
            html_content = f.read()
        return HTMLResponse(content=html_content)
    except FileNotFoundError:
        return JSONResponse(status_code=404, content={"error": "restaurant_finder.html not found"})

@app.get("/restaurants")
def get_restaurants(
    city: Optional[str] = None,
    cuisine: Optional[str] = None,
    price_min: Optional[int] = None,
    price_max: Optional[int] = None,
    top_n: int = 10
):
    data = df.copy()

    if city:
        data = data[data['city'].str.contains(city, case=False, na=False)]

    if cuisine:
        col_name = f"cat_{cuisine}_restaurant"
        if col_name not in data.columns:
            col_name = f"cat_{cuisine}"
        if col_name in data.columns:
            data = data[data[col_name] == 1]

    if price_min is not None:
        data = data[data['price_level'] >= price_min]
    if price_max is not None:
        data = data[data['price_level'] <= price_max]

    data = data.sort_values('predicted_rating', ascending=False).head(top_n)

    #Select only needed columns
    result_cols = ['title', 'city', 'address', 'price_level', 'rating', 'predicted_rating', 'category', 'reviews_total_count']
    existing_cols = [c for c in result_cols if c in data.columns]
    data = data[existing_cols]

    #Convert to serializable records
    records = [make_serializable(row) for _, row in data.iterrows()]
    return records

if __name__ == "__main__":
    import uvicorn
    print("Starting server...")
    print("API documentation available at http://localhost:8000/docs")
    print("Root endpoint: http://localhost:8000/")
    uvicorn.run(app, host="0.0.0.0", port=8000)